spring:
  datasource:
    url: jdbc:mysql://47.96.225.9:3309/gmall_pms?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

dubbo:
  application:
    name: gmall-pms
  registry:
    address: zookeeper://47.96.225.9:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false


